name: recruite_ease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^0.45.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0  # Ensure this version matches your setup
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  image_picker: ^1.0.0
  file_picker: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/admin.png
    - assets/teacher.png
    - assets/student.png
    - assets/job.png
    - assets/coordinator.png
    - assets/student_applied.png
    - assets/notification.png
    - assets/test.png
    - assets/manage_activity.png
    - assets/know_your_job.png


