// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD9I6Img9FdiG5A0vxGMhIzPvYHrp_mUg',
    appId: '1:362544415248:web:574c2d20ee17bdb1ec4095',
    messagingSenderId: '362544415248',
    projectId: 'recruitease-cc7ab',
    authDomain: 'recruitease-cc7ab.firebaseapp.com',
    storageBucket: 'recruitease-cc7ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlGLFLb1kCExBUsnNm2U6QIrGDtplMvi0',
    appId: '1:362544415248:android:e2d462acab829d05ec4095',
    messagingSenderId: '362544415248',
    projectId: 'recruitease-cc7ab',
    storageBucket: 'recruitease-cc7ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_sLp0uRRk8pPLL91ibyoBhd3hCE50Ro',
    appId: '1:362544415248:ios:0d1719705e730ea4ec4095',
    messagingSenderId: '362544415248',
    projectId: 'recruitease-cc7ab',
    storageBucket: 'recruitease-cc7ab.firebasestorage.app',
    iosBundleId: 'com.example.recruiteEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_sLp0uRRk8pPLL91ibyoBhd3hCE50Ro',
    appId: '1:362544415248:ios:0d1719705e730ea4ec4095',
    messagingSenderId: '362544415248',
    projectId: 'recruitease-cc7ab',
    storageBucket: 'recruitease-cc7ab.firebasestorage.app',
    iosBundleId: 'com.example.recruiteEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD9I6Img9FdiG5A0vxGMhIzPvYHrp_mUg',
    appId: '1:362544415248:web:4226d9ed08000a49ec4095',
    messagingSenderId: '362544415248',
    projectId: 'recruitease-cc7ab',
    authDomain: 'recruitease-cc7ab.firebaseapp.com',
    storageBucket: 'recruitease-cc7ab.firebasestorage.app',
  );
}
